version: "3"
services:
  app:
    build: .
    depends_on:
      - postgres
      - redis
    environment:
      PORT: 3000
      PGHOST: postgres
      PGUSER: postgres
      REDIS_URL: redis://redis:6379
    ports:
      - "3000:3000"
    command: npm run start
    volumes:
      - .:/app/
      - /app/node_modules

  postgres:
    image: postgres:15
    ports:
      - "35432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    volumes:
      - ./docs:/app/docs

  redis:
    image: redis/redis-stack-server
    ports:
      - "6379:6379"
