###
GET http://localhost:3000

### Create a user
POST http://localhost:3000/api/users
Content-Type: application/json

{
  "name": "lina",
  "age": 38,
  "location": "florida"
}

### Fetch all users
GET http://localhost:3000/api/users


### Fetch all arts
GET http://localhost:3000/api/art


### Find art by id
GET http://localhost:3000/api/art/20618

### Find art by id
GET http://172.17.0.2/16:3000/api/art/20618

### Add a comment
POST http://localhost:3000/api/art/20618/comments
Content-Type: application/json

{
  "name": "ronathin",
  "content": "i like this lots"
}